# Generated by Django 5.2.9 on 2025-12-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_location_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='district',
            new_name='dist',
        ),
    ]
