# Generated by Django 5.2.9 on 2025-12-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_rename_district_location_dist'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('desc', models.CharField()),
                ('img', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
    ]
