# Generated by Django 5.2.9 on 2026-01-02 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_concellor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='concellor',
            new_name='councellor',
        ),
    ]
