# Generated by Django 5.2.9 on 2026-01-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='councellor',
            name='count',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='councellor',
            name='desc',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='councellor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
