# Generated by Django 5.2.9 on 2026-01-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0009_councellor_count_councellor_desc_councellor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='councellor',
            name='status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject')], default='Processing'),
        ),
    ]
