# Generated by Django 5.2.9 on 2026-01-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0010_councellor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='councellor',
            name='fee',
            field=models.CharField(blank=True, null=True),
        ),
    ]
