# Generated by Django 5.2.9 on 2026-02-17 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('appointmentdate', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked')], default='Processing')),
                ('councellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appontment_councellor', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentdate', models.DateField()),
                ('amount', models.IntegerField()),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appontment_id', to='app_patient.appointment')),
            ],
        ),
    ]
