# Generated by Django 5.2.9 on 2026-01-29 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('appointmentdate', models.DateField()),
                ('councellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appontment_councellor', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
