# Generated by Django 5.2.9 on 2026-02-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0011_councellor_fee'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked')], default='Processing'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentdate', models.DateField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='app_core.councellor')),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appontment_id', to='app_user.appointment')),
            ],
        ),
    ]
