volumes:
  neurosense_local_postgres_data: {}
  neurosense_local_postgres_data_backups: {}
  neurosense_pgadmin_data: {}
  

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: neurosense_local_django
    container_name: neurosense_local_django
    depends_on:
      - postgres
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: neurosense_production_postgres
    container_name: neurosense_local_postgres
    volumes:
      - neurosense_local_postgres_data:/var/lib/postgresql/data
      - neurosense_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
        - "8888:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: test@gmail.com
        PGADMIN_DEFAULT_PASSWORD: test


      volumes:
        - neurosense_pgadmin_data:/var/lib/pgadmin
